# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_subjectgroup_observations = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.io import persist_df as persist_df
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    reproject_gdf as reproject_gdf,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    decompose_datetime as decompose_datetime,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    dedupe_by_column as dedupe_by_column,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    parse_df_point as parse_df_point,
)
from ecoscope_workflows_ext_distance_sample_counts.tasks.transformation import (
    split_weather_by_station_year as split_weather_by_station_year,
)
from ecoscope_workflows_ext_ste.tasks.io import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    spatial_join as spatial_join,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_range") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params.get("groupers") or {}))
        .call()
    )

    weather_er_client = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("weather_er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("weather_er_client") or {}))
        .call()
    )

    weather_subject_group_name = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("weather_subject_group_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("weather_subject_group_name") or {}))
        .call()
    )

    fetch_weather_obs = (
        task(get_subjectgroup_observations)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("fetch_weather_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=weather_er_client,
            subject_group_name=weather_subject_group_name,
            time_range=time_range,
            filter="clean",
            raise_on_empty=False,
            include_details=True,
            include_subjectsource_details=False,
            **(params.get("fetch_weather_obs") or {}),
        )
        .call()
    )

    extract_precipitation = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_precipitation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=fetch_weather_obs,
            column_name="extra__observation_details",
            field_name_options=["precipitation"],
            output_type="float",
            output_column_name="Precipitation",
            **(params.get("extract_precipitation") or {}),
        )
        .call()
    )

    extract_temperature = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_temperature")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_precipitation,
            column_name="extra__observation_details",
            field_name_options=["surface_air_temperature"],
            output_type="float",
            output_column_name="Temperature",
            **(params.get("extract_temperature") or {}),
        )
        .call()
    )

    extract_humidity = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_humidity")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_temperature,
            column_name="extra__observation_details",
            field_name_options=["relative_humidity"],
            output_type="float",
            output_column_name="Humidity",
            **(params.get("extract_humidity") or {}),
        )
        .call()
    )

    extract_wind_speed = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_wind_speed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_humidity,
            column_name="extra__observation_details",
            field_name_options=["wind_speed"],
            output_type="float",
            output_column_name="Windspeed",
            **(params.get("extract_wind_speed") or {}),
        )
        .call()
    )

    fetch_conservancy_boundaries = (
        task(fetch_and_persist_file)
        .validate()
        .set_task_instance_id("fetch_conservancy_boundaries")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/xriwdsjeauzd8akk3oc4b/mara_conservancies.parquet?rlkey=lepz395x9jz3podl39vbke0wh&st=aqzdwmt8&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params.get("fetch_conservancy_boundaries") or {}),
        )
        .call()
    )

    load_conservancy_boundaries = (
        task(load_df)
        .validate()
        .set_task_instance_id("load_conservancy_boundaries")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            file_path=fetch_conservancy_boundaries,
            layer=None,
            deserialize_json=False,
            **(params.get("load_conservancy_boundaries") or {}),
        )
        .call()
    )

    reproject_conservancy_boundaries = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("reproject_conservancy_boundaries")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=load_conservancy_boundaries,
            target_crs="EPSG:4326",
            **(params.get("reproject_conservancy_boundaries") or {}),
        )
        .call()
    )

    weather_conservancy_join = (
        task(spatial_join)
        .validate()
        .set_task_instance_id("weather_conservancy_join")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left_df=extract_wind_speed,
            right_df=reproject_conservancy_boundaries,
            how="inner",
            predicate="intersects",
            **(params.get("weather_conservancy_join") or {}),
        )
        .call()
    )

    rename_weather_identity = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_weather_identity")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=weather_conservancy_join,
            raise_if_not_found=False,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__subject__name": "Station ID",
                "name": "Conservancy",
            },
            **(params.get("rename_weather_identity") or {}),
        )
        .call()
    )

    extract_weather_lat_long = (
        task(parse_df_point)
        .validate()
        .set_task_instance_id("extract_weather_lat_long")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_weather_identity, **(params.get("extract_weather_lat_long") or {})
        )
        .call()
    )

    decompose_weather_fixtime = (
        task(decompose_datetime)
        .validate()
        .set_task_instance_id("decompose_weather_fixtime")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_weather_lat_long,
            datetime_column="fixtime",
            components=["date", "time", "year"],
            remove_source=False,
            column_prefix=None,
            **(params.get("decompose_weather_fixtime") or {}),
        )
        .call()
    )

    rename_weather_datetime = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_weather_datetime")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=decompose_weather_fixtime,
            raise_if_not_found=False,
            drop_columns=[],
            retain_columns=[],
            rename_columns={"fixtime_date": "Date", "fixtime_time": "Time"},
            **(params.get("rename_weather_datetime") or {}),
        )
        .call()
    )

    select_station_metadata = (
        task(select_columns)
        .validate()
        .set_task_instance_id("select_station_metadata")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_weather_datetime,
            columns=["Station ID", "Conservancy", "Latitude", "Longitude"],
            raise_on_missing=True,
            **(params.get("select_station_metadata") or {}),
        )
        .call()
    )

    dedupe_station_metadata = (
        task(dedupe_by_column)
        .validate()
        .set_task_instance_id("dedupe_station_metadata")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=select_station_metadata,
            column="Station ID",
            **(params.get("dedupe_station_metadata") or {}),
        )
        .call()
    )

    persist_station_metadata = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_station_metadata")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=dedupe_station_metadata,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="parquet",
            filename="station_metadata",
            **(params.get("persist_station_metadata") or {}),
        )
        .call()
    )

    station_metadata_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("station_metadata_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=dedupe_station_metadata,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Station Metadata",
            **(params.get("station_metadata_table_html") or {}),
        )
        .call()
    )

    station_metadata_table_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("station_metadata_table_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="station_metadata_table",
            text=station_metadata_table_html,
            **(params.get("station_metadata_table_html_url") or {}),
        )
        .call()
    )

    station_metadata_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("station_metadata_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Station Metadata",
            data=station_metadata_table_html_url,
            **(params.get("station_metadata_table_widget") or {}),
        )
        .call()
    )

    select_weather_readings = (
        task(select_columns)
        .validate()
        .set_task_instance_id("select_weather_readings")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_weather_datetime,
            columns=[
                "Station ID",
                "Precipitation",
                "Humidity",
                "Temperature",
                "Windspeed",
                "fixtime_year",
                "fixtime",
            ],
            raise_on_missing=True,
            **(params.get("select_weather_readings") or {}),
        )
        .call()
    )

    weather_station_year_split = (
        task(split_weather_by_station_year)
        .validate()
        .set_task_instance_id("weather_station_year_split")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=select_weather_readings,
            station_column="Station ID",
            year_column="fixtime_year",
            **(params.get("weather_station_year_split") or {}),
        )
        .call()
    )

    persist_station_year_weather = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_station_year_weather")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="parquet",
            **(params.get("persist_station_year_weather") or {}),
        )
        .mapvalues(argnames=["filename", "df"], argvalues=weather_station_year_split)
    )

    syw_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("syw_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=select_weather_readings,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Station Year Weather Data",
            **(params.get("syw_table_html") or {}),
        )
        .call()
    )

    syw_table_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("syw_table_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="station_year_weather_table",
            text=syw_table_html,
            **(params.get("syw_table_html_url") or {}),
        )
        .call()
    )

    syw_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("syw_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Station Year Weather Data",
            data=syw_table_html_url,
            **(params.get("syw_table_widget") or {}),
        )
        .call()
    )

    overall_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("overall_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[station_metadata_table_widget, syw_table_widget],
            time_range=time_range,
            groupers=groupers,
            **(params.get("overall_dashboard") or {}),
        )
        .call()
    )

    return overall_dashboard
